package com.webank.webase.data.collect.dao.mapper;

import com.webank.webase.data.collect.dao.entity.TbEventInfo;
import com.webank.webase.data.collect.dao.entity.TbEventInfoExample;
import com.webank.webase.data.collect.dao.entity.TbEventInfoExample.Criteria;
import com.webank.webase.data.collect.dao.entity.TbEventInfoExample.Criterion;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbEventInfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     */
    public String countByExample(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        SQL sql = new SQL();
        String tableName = (String) parameter.get("tableName");
        sql.SELECT("count(*)").FROM(tableName);
        //        sql.SELECT("count(*)").FROM(("${tableName}"));
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     */
    public String selectByExampleWithBLOBs(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        String tableName = (String) parameter.get("tableName");
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("contract_name");
        sql.SELECT("contract_address");
        sql.SELECT("user_address");
        sql.SELECT("block_number");
        sql.SELECT("trans_hash");
        sql.SELECT("block_timestamp");
        sql.SELECT("create_time");
        sql.SELECT("modify_time");
        sql.SELECT("event_info");
        sql.FROM((tableName));
        applyWhere(sql, example, true);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public static final String ALL_COLUMN_FIELDS = "id,contract_name,contract_address,user_address,block_number,trans_hash,block_timestamp,create_time,modify_time,event_info";

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String deleteByExample(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        SQL sql = new SQL();
        sql.DELETE_FROM(("${tableName}"));
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String insertSelective(TbEventInfo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO(("${dynamicTableName}"));
        if (record.getContractName() != null) {
            sql.VALUES("contract_name", "#{contractName,jdbcType=VARCHAR}");
        }
        if (record.getContractAddress() != null) {
            sql.VALUES("contract_address", "#{contractAddress,jdbcType=VARCHAR}");
        }
        if (record.getUserAddress() != null) {
            sql.VALUES("user_address", "#{userAddress,jdbcType=VARCHAR}");
        }
        if (record.getBlockNumber() != null) {
            sql.VALUES("block_number", "#{blockNumber,jdbcType=BIGINT}");
        }
        if (record.getTransHash() != null) {
            sql.VALUES("trans_hash", "#{transHash,jdbcType=VARCHAR}");
        }
        if (record.getBlockTimestamp() != null) {
            sql.VALUES("block_timestamp", "#{blockTimestamp,jdbcType=TIMESTAMP}");
        }
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.VALUES("modify_time", "#{modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getEventInfo() != null) {
            sql.VALUES("event_info", "#{eventInfo,jdbcType=LONGVARCHAR}");
        }
        return sql.toString();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String selectByExample(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("contract_name");
        sql.SELECT("contract_address");
        sql.SELECT("user_address");
        sql.SELECT("block_number");
        sql.SELECT("trans_hash");
        sql.SELECT("block_timestamp");
        sql.SELECT("create_time");
        sql.SELECT("modify_time");
        sql.FROM(("${tableName}"));
        applyWhere(sql, example, true);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        // add pagination for mysql with limit clause 
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        if (example != null && (example.getStart() > -1 || example.getCount() > -1)) {
            sqlBuilder.append(" limit ");
            if (example.getStart() > -1 && example.getCount() > -1) {
                sqlBuilder.append(example.getStart()).append(",").append(example.getCount());
            } else if (example.getStart() > -1) {
                sqlBuilder.append(example.getStart());
            } else if (example.getCount() > -1) {
                sqlBuilder.append(example.getCount());
            }
        }
        return sqlBuilder.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        TbEventInfo record = (TbEventInfo) parameter.get("record");
        SQL sql = new SQL();
        sql.UPDATE(("${tableName}"));
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        if (record.getContractName() != null) {
            sql.SET("contract_name = #{record.contractName,jdbcType=VARCHAR}");
        }
        if (record.getContractAddress() != null) {
            sql.SET("contract_address = #{record.contractAddress,jdbcType=VARCHAR}");
        }
        if (record.getUserAddress() != null) {
            sql.SET("user_address = #{record.userAddress,jdbcType=VARCHAR}");
        }
        if (record.getBlockNumber() != null) {
            sql.SET("block_number = #{record.blockNumber,jdbcType=BIGINT}");
        }
        if (record.getTransHash() != null) {
            sql.SET("trans_hash = #{record.transHash,jdbcType=VARCHAR}");
        }
        if (record.getBlockTimestamp() != null) {
            sql.SET("block_timestamp = #{record.blockTimestamp,jdbcType=TIMESTAMP}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getEventInfo() != null) {
            sql.SET("event_info = #{record.eventInfo,jdbcType=LONGVARCHAR}");
        }
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        SQL sql = new SQL();
        sql.UPDATE(("${tableName}"));
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("contract_name = #{record.contractName,jdbcType=VARCHAR}");
        sql.SET("contract_address = #{record.contractAddress,jdbcType=VARCHAR}");
        sql.SET("user_address = #{record.userAddress,jdbcType=VARCHAR}");
        sql.SET("block_number = #{record.blockNumber,jdbcType=BIGINT}");
        sql.SET("trans_hash = #{record.transHash,jdbcType=VARCHAR}");
        sql.SET("block_timestamp = #{record.blockTimestamp,jdbcType=TIMESTAMP}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        sql.SET("event_info = #{record.eventInfo,jdbcType=LONGVARCHAR}");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        SQL sql = new SQL();
        sql.UPDATE(("${tableName}"));
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("contract_name = #{record.contractName,jdbcType=VARCHAR}");
        sql.SET("contract_address = #{record.contractAddress,jdbcType=VARCHAR}");
        sql.SET("user_address = #{record.userAddress,jdbcType=VARCHAR}");
        sql.SET("block_number = #{record.blockNumber,jdbcType=BIGINT}");
        sql.SET("trans_hash = #{record.transHash,jdbcType=VARCHAR}");
        sql.SET("block_timestamp = #{record.blockTimestamp,jdbcType=TIMESTAMP}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Map<String, Object> parameter) {
        TbEventInfo record = (TbEventInfo) parameter.get("record");
        SQL sql = new SQL();
        sql.UPDATE(("${tableName}"));
        if (record.getContractName() != null) {
            sql.SET("contract_name = #{record.contractName,jdbcType=VARCHAR}");
        }
        if (record.getContractAddress() != null) {
            sql.SET("contract_address = #{record.contractAddress,jdbcType=VARCHAR}");
        }
        if (record.getUserAddress() != null) {
            sql.SET("user_address = #{record.userAddress,jdbcType=VARCHAR}");
        }
        if (record.getBlockNumber() != null) {
            sql.SET("block_number = #{record.blockNumber,jdbcType=BIGINT}");
        }
        if (record.getTransHash() != null) {
            sql.SET("trans_hash = #{record.transHash,jdbcType=VARCHAR}");
        }
        if (record.getBlockTimestamp() != null) {
            sql.SET("block_timestamp = #{record.blockTimestamp,jdbcType=TIMESTAMP}");
        }
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        if (record.getModifyTime() != null) {
            sql.SET("modify_time = #{record.modifyTime,jdbcType=TIMESTAMP}");
        }
        if (record.getEventInfo() != null) {
            sql.SET("event_info = #{record.eventInfo,jdbcType=LONGVARCHAR}");
        }
        sql.WHERE("id = #{record.id,jdbcType=INTEGER}");
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TbEventInfoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_event_info
     *
     * @mbg.generated
     */
    public String getOneByExample(Map<String, Object> parameter) {
        TbEventInfoExample example = (TbEventInfoExample) parameter.get("example");
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("contract_name");
        sql.SELECT("contract_address");
        sql.SELECT("user_address");
        sql.SELECT("block_number");
        sql.SELECT("trans_hash");
        sql.SELECT("block_timestamp");
        sql.SELECT("create_time");
        sql.SELECT("modify_time");
        sql.SELECT("event_info");
        sql.FROM(("${tableName}"));
        applyWhere(sql, example, true);
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        StringBuilder sqlBuilder = new StringBuilder(sql.toString());
        sqlBuilder.append(" limit 1 ");
        return sqlBuilder.toString();
    }
}
