# server config
server:
  port: 5010
  servlet:
    context-path: /WeBASE-Data-Fetcher

# database connection configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/webasedata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: "defaultAccount"
    password: "defaultPassword"
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:5300
  main:
    allow-bean-definition-overriding: true

# mybatis config
mybatis:
  typeAliasesPackage: com.webank.webase.data.fetcher
  mapperLocations: classpath:mapper/*.xml
 
# log config
logging:
  config: classpath:log/log4j2-dev.xml
  level:
    com.webank.webase.data.fetcher: info
