package com.webank.webase.data.collect.dao.entity;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.Accessors;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
@Accessors(chain = true)
public class TbGasReconciliation implements Serializable {

    public TbGasReconciliation(Integer chainId, Integer groupId, String userAddress) {
        this.chainId = chainId;
        this.groupId = groupId;
        this.userAddress = userAddress;
    }

    public TbGasReconciliation(Byte reconciliationStatus) {
        this.reconciliationStatus = reconciliationStatus;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.block_number
     *
     */
    private BigInteger blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.create_time
     *
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.modify_time
     *
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.chain_id
     *
     * @mbg.generated
     */
    private Integer chainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.user_address
     *
     * @mbg.generated
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.trans_hash
     *
     * @mbg.generated
     */
    private String transHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas_reconciliation.reconciliation_status
     *
     * @mbg.generated
     */
    private Byte reconciliationStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_gas_reconciliation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
