package com.webank.webase.data.collect.dao.entity;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode
public class TbGas implements Serializable {

    public TbGas(Integer chainId, Integer groupId, BigInteger blockNumber, String transHash,
            LocalDateTime blockTimestamp, String userAddress, BigInteger gasValue,
            BigInteger gasRemain, Integer recordMonth, Byte recordType) {
        this.chainId = chainId;
        this.groupId = groupId;
        this.blockNumber = blockNumber;
        this.transHash = transHash;
        this.blockTimestamp = blockTimestamp;
        this.userAddress = userAddress;
        this.gasValue = gasValue;
        this.gasRemain = gasRemain;
        this.recordMonth = recordMonth;
        this.recordType = recordType;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.block_number
     *
     */
    private BigInteger blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.block_timestamp
     *
     */
    private LocalDateTime blockTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.gas_value
     *
     */
    private BigInteger gasValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.create_time
     *
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.modify_time
     *
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.record_month
     *
     * @mbg.generated
     */
    private Integer recordMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.chain_id
     *
     * @mbg.generated
     */
    private Integer chainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.trans_hash
     *
     * @mbg.generated
     */
    private String transHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.user_address
     *
     * @mbg.generated
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.record_type
     *
     * @mbg.generated
     */
    private Byte recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_gas.gas_remain
     *
     */
    private BigInteger gasRemain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_gas
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
